### PR TITLE
Project Submission

### PR DESCRIPTION
**Pull request by rutujak24**
Project Submission for Study Jam 2.0 by Rutuja Kawade for Microsoft Azure Machine Learning Program Phase 1.

Slack ID: Rutuja Kawade
Email ID: rutujakawade24@gmail.com

### CODE REVIEW

**Comment by Iamsdt** [comment]
Hello,
Can you move your all files under **project** folder
Currently, you added all your files in the root directory.
Please move into the **project folder**

**Comment by rutujak24** [comment]
Done

**Comment by Iamsdt** [comment]
Thank you very much for the update.

**Participants must submit the following materials:

1. Project proposal: Markdown file (ReadMe.md) which explains the project and the team: Team members’ name; what the project does; who the project is for; used technology, etc.
2.Project Implementation: Juyter notebook and/or pdf file and/or Presentation video (1 to 3 minute) pitch.**

You missed the first options. Please add read me file.

**Comment by rutujak24** [comment]
please close this PR, I will create a new PR asap

**Comment by Iamsdt** [comment]
@rutujak24 Ok I am closing the PR

**Pull request closed without merging**
